apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  username: {{ .Values.mongodb.username | b64enc | quote }}
  password: {{ .Values.mongodb.password | b64enc | quote }}
