apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres-ns
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
