apiVersion: v1
kind: Service
metadata:
  name: cpu-monitor
spec:
  type: NodePort
  selector:
    app: cpu-monitor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007