apiVersion: v1
kind: Pod
metadata:
  name: example-2
spec:
  containers:
  - name: busybox
    image: busybox
    args:
     - while true; do echo -en '\n'; printf SERVICE_NAME=$SERVICE_NAME'\n'; sleep 3; done;
    command:
     - sh
     - -c
    env:
    - name: PORT
      value: "8080"
    - name: SERVICE_NAME
      value: "my-application"