apiVersion: v1
kind: Pod
metadata:
  name: example-1
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sleep
    - "3600"  # 1 hour
    env:
    - name: PORT
      value: "8080"
    - name: SERVICE_NAME
      value: "example-1"
      