apiVersion: v1
kind: Pod
metadata:
  name: example-3
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "env"]
    env:
    - name: VAR1
      valueFrom:
        configMapKeyRef:
          name: app-properties
          key: var1
    - name: VAR2
      valueFrom:
        configMapKeyRef:
          name: app-properties
          key: var2