apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: node-app
spec:
  selector:
    app: node-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30012
