---
- name: Manage files on remote hosts
  hosts: all
  tasks:
    - name: Create a directory
      file:
        path: /tmp/example_directory
        state: directory

    - name: Create a file
      file:
        path: /tmp/example_directory/example_file.txt
        state: touch

    - name: Remove a file
      file:
        path: /tmp/example_directory/example_file.txt
        state: absent 