apiVersion: v1
kind: Service
metadata:
  name: spring-boot-hpa-service
spec:
  selector:
    app: spring-boot-hpa-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: NodePort
