# book-crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: books.library.bansikah.com
spec:
  group: library.bansikah.com
  names:
    plural: books
    singular: book
    kind: Book
    shortNames:
      - bk
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
                publishedDate:
                  type: string
                availableCopies:
                  type: integer
