{{- if .Values.rbac.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: grafana
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: grafana
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: grafana
  apiGroup: rbac.authorization.k8s.io
{{- end }}