apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service
  labels:
    component: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080  
  selector:
    component: nginx
  type: NodePort  
