name: Code Review
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  ai_code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run AI PR Reviewer
        uses: coderabbitai/ai-pr-reviewer@latest
        with:
          openai_light_model: 'gpt-3.5-turbo'
          openai_heavy_model: 'gpt-4'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
