name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Welcome to the DevOps Tools repository! 🚀
          - Please read the [CONTRIBUTING.md](./CONTRIBUTING.md) file before raising an issue.
          - If you're working on **Jenkins**, **Kubernetes**, or other tools, ensure your issue includes necessary details to reproduce it.
        pr-message: |
          Thank you for your first pull request! 🎉
          - Before merging, please confirm that your changes adhere to the guidelines in [CONTRIBUTING.md](./CONTRIBUTING.md).
          - Let's keep the repository organized and robust for everyone!
          - If you're working on **Jenkins**, **Kubernetes**, or other tools, ensure your pull request includes necessary details to reproduce it.