name: Pre-Merge Checks

on:
  pull_request:
    branches:
      - main  # Trigger for PRs targeting the master branch

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Code linting for Python or JavaScript (adjust based on your repo)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies (if using Python)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Lint code using flake8 (for Python) or eslint (for JavaScript)
      - name: Lint Python code
        run: flake8 .

      # Optionally, you could include a step for tests (if any)
      - name: Run tests
        run: pytest

  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Dependency security scan (Safety for Python, or npm audit for JS)
      - name: Run dependency security check
        run: |
          pip install safety
          safety check --full-report  # For Python projects

  pr_template_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR template
        uses: enriclluelles/ensure-pr-template@v1
        with:
          template_path: '.github/PULL_REQUEST_TEMPLATE.md'

  license_check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Fossa CLI
        run: |
          curl -sSL https://github.com/fossa/fossa-cli/releases/download/v0.6.2/fossa-cli-linux-amd64-0.6.2.tar.gz | tar -xzv
          sudo mv fossa /usr/local/bin

      - name: Run Fossa scan
        run: |
          fossa init
          fossa analyze --skip-license-check=false  # Ensure license compliance
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}

  dockerfile_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install `hadolint` for Dockerfile linting
      - name: Install hadolint
        run: |
          curl -sSL https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
          chmod +x /usr/local/bin/hadolint

      - name: Run Dockerfile lint
        run: hadolint Dockerfile  # Adjust this path to your Dockerfile

